name: build

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.18]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: oci-help

      - name: Install dependencies
        run: |
          docker pull techknowlogick/xgo:latest
          go install src.techknowlogick.com/xgo@latest
          sudo apt install upx

      - name: Build
        run: |
          mv oci-help/build.sh .
          bash build.sh build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: oci-help/build